killall -9 crex_tests
killall -9 $CMAKE_PREFIX_PATH/bin/orogen_default_trajectory_generation__Task
killall -9 $CMAKE_PREFIX_PATH/bin/orogen_default_behavior_graph__MotionControlTask
killall -9 $CMAKE_PREFIX_PATH/bin/orogen_default_skid4_control__SimpleController
killall -9 $CMAKE_PREFIX_PATH/bin/orogen_default_joint_dispatcher__Task
